services:
  advent_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: advent_php_app
    working_dir: /var/www/html
    volumes:
      - ./api:/var/www/html
    depends_on:
      - advent_postgres
    networks:
      - advent_laravel_network
    command: php-fpm

  advent_nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: advent_nginx_server
    volumes:
      - ./:/var/www/html
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
    ports:
      - "${APP_PORT}:80"
      - "443:443"
    depends_on:
      - advent_app
    networks:
      - advent_laravel_network
    environment:
      - SERVER_NAME=${APP_DOMAIN}
      - ENVIRONMENT=${APP_ENV}
      - API_SERVER_NAME=${APP_API_DOMAIN}

  advent_certbot:
    image: certbot/certbot:v3.1.0
    container_name: advent_certbot
    volumes:
      - ./nginx/certbot/conf:/etc/letsencrypt
      - ./nginx/certbot/www:/var/www/certbot
      - ./:/var/www/html
    networks:
      - advent_laravel_network
    depends_on:
      - advent_nginx

  advent_postgres:
    image: postgres:17
    container_name: advent_postgres_db
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - advent_laravel_network

  advent_mongo:
    image: mongo:8
    container_name: advent_mongo_db
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - advent_laravel_network

  advent_node:
    image: node:current-alpine3.21
    container_name: advent_node_server
    working_dir: /var/www/html
    command: sh -c "npm install -g pnpm && pnpm config set store-dir /root/.pnpm-store && tail -f /dev/null"
    volumes:
      - ./frontend:/var/www/html
    ports:
      - "5173:5173"
    networks:
      - advent_laravel_network

networks:
  advent_laravel_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data: